name: Run tests

on:
  push:

jobs:
  test:
    name: "Run tests"
    runs-on: ubuntu-latest
    env:
      RAILS_VERSION: ${{ matrix.rails-version }}
    strategy:
      matrix:
        include:
          - ruby-version: '3.2'
            rails-version: '6.1'
          - ruby-version: '3.2'
            rails-version: '7.0'
          - ruby-version: '3.2'
            rails-version: '7.1'
          - ruby-version: '3.3'
            rails-version: '7.1'
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Run RSpec
        run: bundle exec rspec
